@startuml

node "Prometheus Server" {
	[Prometheus]
}

node "Server" as ProxyServer {
	[Proxy exporter]
}

node "Server" as SidecarServer {
	[Sidecar exporter]
	[application] as sidecar_app
	[Sidecar exporter] --> sidecar_app : Protocol
}

node "Server" as NativeServer {
	frame "application" {
		[Native exporter]
		[application] as native_app
	}
	[Native exporter] --> native_app
}

node "Target" as Target1 {
	[service] as service1
}

node "Target" as Target2 {
	[service] as service2
}

node "Target" as Target3 {
	[DNS]
}

node "Target" as Target4 {
	[Host]
}

node "Target" as Target5 {
	[SNMP]
}

[Prometheus] --> [Proxy exporter] : HTTP
[Prometheus] --> [Sidecar exporter] : HTTP
[Prometheus] --> [Native exporter] : HTTP

[Proxy exporter] --> [Host] : ICMP
[Proxy exporter] --> service1 : TCP
[Proxy exporter] --> service2 : HTTP
[Proxy exporter] --> [DNS] : DNS
[Proxy exporter] --> [SNMP]: SNMP

@enduml
