@startuml

actor "ログ検索・Graylog設定" as user

[ログ転送エージェント] -down-> [エンドポイント]

[エンドポイント] -down-> [Graylog slave]

[Graylog slave] -down-> [Elasticsearch]

user -down-> [Graylog master]

[Graylog master] -down-> [MongoDB]

[Graylog slave] -down-> [MongoDB]

@enduml
