@startuml

cloud "コントロールパネル"

node "エンドポイント" as endpoint {
	[Nginx]
}

node "Server" as cacti-server {
	[cacti-graph-api]
	[Cacti] -down-> [MySQL]
}

コントロールパネル -down-> [Nginx]
[Nginx] -down-> [cacti-graph-api]
[cacti-graph-api] -down-> [MySQL]

@enduml
